app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, send_file, request
from app.models import User, BaseballCard
from app.forms import LoginForm, RegistrationForm, AddCardForm, SortCardsForm
from flask_login import login_user, logout_user, login_required, current_user
from app import db
from sqlalchemy import func
from PIL import Image
import io
import os
import magic
import pillow_heif
import fitz

main_routes = Blueprint('main', __name__)


@main_routes.route('/')
def home():
    return render_template('landing.html')


@main_routes.route('/image')
def image():
    card_id = request.args.get('card_id')
    if not card_id:
        flash('Card id not given.')
        return render_template('index.html')
    card = db.session.query(BaseballCard).get(card_id)
    if not card or not card.picture:
        flash('Cards not found.')
        return render_template('index.html')

    mime = magic.Magic(mime=True)
    mime_type = mime.from_buffer(card.picture)

    img_io = io.BytesIO(card.picture)

    if mime_type == 'application/pdf':
        pdf_document = fitz.open(stream=img_io, filetype="pdf")
        first_page = pdf_document.load_page(0)  # Load the first page
        pix = first_page.get_pixmap()
        img_data = pix.tobytes("png")
        img = Image.open(io.BytesIO(img_data))
    elif mime_type == 'image/heic':
        heif_file = pillow_heif.read_heif(img_io)
        img = Image.frombytes(
            heif_file.mode, 
            heif_file.size, 
            heif_file.data,
            "raw",
            heif_file.mode,
            heif_file.stride,
        )
    else:
        img = Image.open(img_io)


    output_io = io.BytesIO()
    img.save(output_io, 'JPEG')
    output_io.seek(0)
    
    return send_file(
        output_io,
        mimetype='image/jpeg',
        as_attachment=False,
    )

    # mime = magic.Magic(mime=True)
    # mime_type = mime.from_buffer(card.picture)
    # return send_file(
    #     io.BytesIO(card.picture),
    #     mimetype=mime_type,
    #     as_attachment=False,
    # )
     
@main_routes.route('/collections')
def collections():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(User.username.asc()).paginate(
        page=page, per_page=5, error_out=False)
    users = pagination.items
    count = User.query.count()
    return render_template('collections.html', users=users, pagination=pagination, count=count)


@main_routes.route('/card/<int:card_id>')
@login_required
def view_card(card_id):
    card = BaseballCard.query.filter_by(id=card_id).first()
    return render_template('view-card.html', card=card)

@main_routes.route('/user', defaults={'user_id': None}, methods=['GET', 'POST'])
@main_routes.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
def user_profile(user_id):
    form = SortCardsForm()
    if user_id is None:
        user_id = current_user.id
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        flash('User not found.')
        return render_template('index.html')
    if form.validate_on_submit():
        sort_by = form.sort_by.data
        return redirect(url_for('main.user_profile', user_id=user_id, sort=sort_by))
    sort_by = request.args.get('sort', 'name', type=str)
    page = request.args.get('page', 1, type=int)
    pagination = user.cards.order_by(func.lower(getattr(BaseballCard, sort_by))).paginate(
        page=page, per_page=5, error_out=False)
    cards = pagination.items
    return render_template('profile.html', user=user, cards=cards, form=form, pagination=pagination, sort=sort_by)


@main_routes.route('/add-card', methods=['GET', 'POST'])
@login_required
def add_card():
    form = AddCardForm()
    if form.validate_on_submit():
        card = BaseballCard(name=form.name.data, position=form.position.data, team=form.team.data,
                            year=form.year.data, user_id=current_user.id)
        if form.picture.data:
            card.picture = form.picture.data.read()
        else:
            default_image_path = os.path.join(os.path.dirname(__file__), 'static', 'default.png')
            card.picture = open(default_image_path, 'rb').read()
        db.session.add(card)
        db.session.commit()
        return redirect(url_for('main.add_card'))
    return render_template('add-card.html', form=form)


auth_routes = Blueprint('auth', __name__)


@auth_routes.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged in.')
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            return redirect(url_for('main.user_profile', user_id=user.id))
        flash('Invalid email or password.')
    return render_template('login.html', form=form)


@auth_routes.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.create_password(form.password.data)
        if User.query.filter_by(username=user.username).first():
            flash('Username already in use.')
            return redirect(url_for('auth.register'))
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('auth.login'))
    return render_template('register.html', form=form)


@auth_routes.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.home'))

app/templates/add-card.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Add Cards{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Add Cards</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}App{% endblock %}

{% block head %}
{{ super() }}
<link rel="icon" href="{{ url_for('static', filename='default.png') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.home') }}">CardVault</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.user_profile') }}">Your Collection</a></li>
                <li><a href="{{ url_for('main.add_card') }}">Add Cards</a></li>
                <li><a href="{{ url_for('main.collections') }}">Collections</a></li>
            
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                
                
            </ul>
        </div>
    </div>
</div>
{% endblock %}




{% block content %}
<div class="content">
    <div class="container">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        {% block page_content %}
        {% endblock %}
    </div>
</div>
<footer class="footer">
    <div class="container">
        <p>&copy; 2024 CardVault</p>
    </div>
</footer>
{% endblock %}




{% block styles %}
{{super()}}
<style>
    html {
        height: 100%;
    }
    body {
        min-height: 100%;
        display: flex;
        flex-direction: column;
    }
    .content {
        flex: 1 0 auto;
    }
    .footer {
        flex-shrink: 0;
        background-color: #f5f5f5;
        text-align: center;
        padding: 10px 0;
        margin-top: 20px;
    }
</style>
{% endblock %}

app/templates/collections.html
{% extends "base.html" %}
{% import "macros.html" as macros %}
{% block title %}User Collections{% endblock %}


{% block page_content %}
<div class="page-header">
    <h1>{{ count }} collections available:</h1>
    {% for user in users %}
        <div class="user-section" style="margin-bottom: 20px;">
            <h2>
                <span class="heading-container">
                    <a href="{{ url_for('main.user_profile', user_id=user.id) }}">{{ user.username }}</a> has {{ user.cards.count() }} cards, including:
                </span>
            </h2>
            <ul style="list-style-type: none; padding: 0; display: flex; flex-wrap: wrap;">
                {% for card in user.cards[:6] %}
                    <li style="margin-right: 10px; margin-bottom: 10px;">
                        <h3>{{ card.name }}</h3>
                        <div>
                            <a href="{{ url_for('main.view_card', card_id=card.id) }}"> 
                            <img src="{{ url_for('main.image', card_id=card.id) }}" alt="{{ card.name }}" style="width: 200px; height: auto;"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    {% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.collections') }}
</div>
{% endif %}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.id}}{% else %}Stranger{% endif %}!</h1>
</div>
{% endblock %}
{% block footer %}{% endblock %}

app/templates/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CardVault</title>
    <link rel="stylesheet" href="static/style.css">
</head>
<body>
    <header>
        <nav>
            <div class="logo">CardVault</div>
             
            <ul>
                <li><a href="{{ url_for('main.collections') }}">View Collections</a></li>
                <li><a href="{{ url_for('auth.register') }}">Sign up</a></li>
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section id="hero">
            <h1>CardVault</h1>
            <p>CardVault lets you keep track and put on display your favorite baseball cards! </p>
            <a href="{{ url_for('auth.register') }}" class="cta-button">Get Started</a>
        </section>

        <section id="features">
            <h2>Key Features</h2>
            <div class="feature-container">
                <div class="feature">
                    <img src="placeholder1.jpg" alt="Feature 1" class="feature-image">
                    <h3>Feature 1</h3>
                    <p>Description of feature 1.</p>
                </div>
                <div class="feature">
                    <img src="placeholder2.jpg" alt="Feature 2" class="feature-image">
                    <h3>Feature 2</h3>
                    <p>Description of feature 2.</p>
                </div>
                <div class="feature">
                    <img src="placeholder3.jpg" alt="Feature 3" class="feature-image">
                    <h3>Feature 3</h3>
                    <p>Description of feature 3.</p>
                </div>
            </div>
        </section>

        <section id="about">
            <h2>About Us</h2>
            <p>Information about your company or app goes here.</p>
        </section>

        <section id="contact">
            <h2>Contact Us</h2>
            <form>
                <input type="text" placeholder="Name" required>
                <input type="email" placeholder="Email" required>
                <textarea placeholder="Message" required></textarea>
                <button type="submit">Send</button>
            </form>
        </section>
    </main>

    <footer>
        <p> 2024 CardVault. All rights reserved.</p>
    </footer>
</body>
</html>

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Login</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
    <br>
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endblock %}

app/templates/macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, sort=sort_by, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, sort=sort_by, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, sort=sort_by, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, sort=sort_by, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "macros.html" as macros %}
{% block title %}Collection{% endblock %}

{% block page_content %}
<div class="page-header">
    
    <div class="col-md-4">
        <h1>{{ user.username }}'s Cards</h1>
        {{ wtf.quick_form(form) }}
    </div>
    <ul style="list-style-type: none; padding: 0; display: flex; flex-wrap: wrap;">
        {% for card in cards %}
            <li style="margin-right: 10px; margin-bottom: 10px;">
                <h2>{{ card.name }}</h2>
                <div>
                    <a href="{{ url_for('main.view_card', card_id=card.id) }}">
                    <img src="{{ url_for('main.image', card_id=card.id) }}" alt="{{ card.name }}" style="width: 200px; height: auto;"></a>
                </div>
            </li>
        {% endfor %}
    </ul>
    {% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.user_profile', sort) }}
</div>
{% endif %}

        

</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Register{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Register</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/view-card.html
{% extends "base.html" %}

{% block title %}User Card{% endblock %}


{% block page_content %}
<div class="page-header">
    <h1>Card</h1>
    <div>
        <h2>Name: {{ card.name }}</h2>
        <h2>Position: {{ card.team }}</h2>
        <h2>Team: {{ card.year }}</h2>
        <h2>Year: {{ card.year }}</h2>
        <img src="{{ url_for('main.image', card_id=card.id) }}" alt="{{ card.name }}" style="width: 200px; height: auto;"> 
    </div>
</div>
{% endblock %}